---
version: "3"
services:
  ipfs:
    image: ipfs/kubo:v0.29.0
    container_name: ipfs
    restart: unless-stopped
    volumes:
      - ipfs_path:/data/ipfs
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
      - ./files:/export:ro
    environment:
      - IPFS_PATH=/data/ipfs
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 127.0.0.1:5001:5001
      - 127.0.0.1:8080:8080
    networks:
      - caddy_net

volumes:
  ipfs_path:
  ipfs_fuse:
  ipns_fuse:

networks:
  caddy_net:
    name: caddy_net
    driver: bridge
