languageCode = 'en-us'
title = 'UPO TFM'
# theme = 'PaperMod'
theme = 'terminal'
baseURL = 'https://upo.ducktective.org'

[taxonomies]
tag = "tags"
category = "categories"

[params]
centerTheme = true

[languages.en.params.logo]
logoText = "UPO TFM: Guerrilla Storage"
logoHomeLink = "/"
